docs: add contributing, code of conduct, codowners, and readme files
liatrio/image-builder-terraform pull request #4
Opened 2022-07-18 20:43 UTC by Micahperez2

2022-07-18 21:06 UTC, austinjw submitted a review, later dismissed

2022-07-18 21:06 UTC, austinjw commented on README.md
> +The image's intendended purpose is to be able to be used as a reusable image to be used as a jenkins agent. By using the installed features the user is able to create jenkins pipeline that can trigge
The intended purpose of this image is for it to be used as a Jenkins agent. By using the installed features the user is able to create Jenkins pipelines that can trigger Terraform scripts to deploy and update infrastructure. Additionally, Terragrunt gives the ability to use extra tools for Terraform.

2022-07-18 21:06 UTC, austinjw commented on README.md
> +For this workflow to run, the only thing that needs to be input is a user or organizations `GITHUB_TOKEN` into the secrets of the repo.
For this workflow to run, the only thing that needs to be input is a user or organizations `GITHUB_TOKEN`, which is automatically provided by GitHub Actions.

2022-07-19 15:58 UTC, ChrisSchreiber requested changes

2022-07-19 15:58 UTC, ChrisSchreiber commented on README.md
> +The intended purpose of this image is for it to be used as a Jenkins agent. By using the installed features the user is able to create Jenkins pipelines that can trigger Terraform scripts to deploy a
Lets put his at the top and include some sample code for configuring the agent and using it in the pipeline... for reference https://plugins.jenkins.io/kubernetes/ https://github.com/liatrio/springtrader/blob/solution2/Jenkinsfile

2022-07-19 15:58 UTC, ChrisSchreiber commented on README.md
> +This repository contains a workflow that creates a current release tag and then uses the [build-scan-push](https://github.com/liatrio/github-workflows/blob/main/.github/workflows/build-scan-push.yaml
Lets move this down into a sections called Build

2022-07-19 17:17 UTC, austinjw approved these changes

2022-07-19 19:57 UTC, ChrisSchreiber approved these changes

2022-07-19 19:58 UTC, merged